# Generated by Django 4.2.6 on 2023-11-09 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="turn",
        ),
        migrations.RemoveField(
            model_name="hand",
            name="player",
        ),
        migrations.AddField(
            model_name="game",
            name="currentTurn",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="game",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="game.game"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="hand",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="game.hand"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
