# Generated by Django 4.2.6 on 2023-12-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='currentBetAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='isDrawingRound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='isFirstBetRound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='isSecondBetRound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='playersPassed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='turnOrder',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hand',
            name='ratingOut',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='hand',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='canCheck',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='discardedCards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='doneDrawing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='drawnCards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='totalAmountBet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.CharField(choices=[('02', 'Two'), ('03', 'Three'), ('04', 'Four'), ('05', 'Five'), ('06', 'Six'), ('07', 'Seven'), ('08', 'Eight'), ('09', 'Nine'), ('10', 'Ten'), ('11', 'Jack'), ('12', 'Queen'), ('13', 'King'), ('14', 'Ace')], max_length=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pot',
            name='moneyAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
