# Generated by Django 4.2.6 on 2023-10-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fivecarddraw", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Todo", new_name="fivecarddraw",),
    ]
