# Generated by Django 4.2.6 on 2023-11-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_backing',
            field=models.TextField(blank=True, choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], max_length=500, null=True),
        ),
    ]
