# Generated by Django 4.2.6 on 2023-11-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='table_theme',
            field=models.TextField(blank=True, choices=[('blue', 'Blue'), ('green', 'Green')], max_length=500, null=True),
        ),
    ]
