# Generated by Django 4.2.6 on 2023-11-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
