# Generated by Django 4.2.7 on 2023-12-05 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('group_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('chat_type', models.CharField(blank=True, choices=[('global', 'Global'), ('game', 'Game'), ('friend', 'Friend')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar_color', models.TextField(blank=True, max_length=500, null=True)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('chatter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatter')),
            ],
        ),
    ]
